import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Login from "@/component/Login";
import Register from "@/component/Register";
import UserAuth from "@/component/UserAuth";

function Home() {
  const [tab, setTab] = useState<"login" | "register">("login");
  return (
    <>
      <Head>
        <title>DOT CHALENGE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.form_wrap}>
          <nav className={`${styles.tab_group}`}>
            <p
              className={`${styles.tab} ${
                tab === "login" && styles.tab_select
              }`}
              onClick={() => setTab("login")}
            >
              Login
            </p>
            <p
              className={`${styles.tab} ${
                tab === "register" && styles.tab_select
              }`}
              onClick={() => setTab("register")}
            >
              Daftar Baru
            </p>
          </nav>
          <section className={styles.content}>
            {tab === "login" && <Login />}
            {tab === "register" && <Register />}
          </section>
        </section>
      </main>
    </>
  );
}

export default function Page() {
  <UserAuth>
    <Home />
  </UserAuth>;
}
